services:
  web:
    build:
      dockerfile: ./setup/web-dockerfile
      args:
      - UID=${UID:-1001}
      - GID=${GID:-1001}
    ports:
      - '80:80'
    volumes:
      - ./public/:/www/esit/public
      - ./include/:/www/esit/include
      - ./setup/nginx.conf.example:/etc/nginx/nginx.conf
      - ./setup/default.conf.example:/etc/nginx/conf.d/default.conf
      - ./setup/fastcgi-php.conf.example:/etc/nginx/snippets/fastcgi-php.conf
    depends_on:
      - worker
  
  php-fpm:
    build:
      dockerfile: ./setup/php-dockerfile
      args:
      - UID=${UID:-1001}
      - GID=${GID:-1001}
    volumes:
      - ./public/index.php:/www/esit/public/index.php
      - ./public/app/content:/www/esit/public/app/content
      - ./public/img:/www/esit/public/img
      - ./public/include/resources:/www/esit/public/include/resources
      - ./include/:/www/esit/include
    depends_on:
      - rabbitmq

  mysql:
    build:
      dockerfile: ./setup/mysql-dockerfile
    environment:
      MYSQL_ROOT_PASSWORD: esit_db_root
      MYSQL_DATABASE: esit_db
      MYSQL_USER: esit_db
      MYSQL_PASSWORD: esit_db
    depends_on:
      - php-fpm

  rabbitmq:
    image: rabbitmq:4.1-alpine
    environment:
      RABBITMQ_DEFAULT_USER: esit_user
      RABBITMQ_DEFAULT_PASS: 123456
      RABBITMQ_MANAGEMENT.LOAD_DEFINITIONS: /etc/rabbitmq/rabbitmq-definitions.json
    volumes:
      - ./setup/rabbitmq-enabled-plugins.example:/etc/rabbitmq/enabled_plugins
      - ./setup/definitions.rabbitmq.json.example:/etc/rabbitmq/definitions.json
      - ./setup/rabbitmq.config.example:/etc/rabbitmq/rabbitmq.conf

  worker:
    build:
      dockerfile: ./setup/worker-dockerfile
    volumes:
      - ./worker/:/worker/
    privileged: true
    command: python3 /worker/mq_receiver.py
    depends_on:
      - mysql